version: "3.8"
services:
  backend:
    image: priyanshugupta753/backend:latest
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/birth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://192.168.200.226:8081/realms/LeaveApplication
      KEYCLOAK_REALM: LeaveApplication
      KEYCLOAK_AUTH_SERVER_URL: http://192.168.200.226:8081/auth
      KEYCLOAK_RESOURCE: leave_application
      KEYCLOAK_PUBLIC_CLIENT: "true"
      KEYCLOAK_BEARER_ONLY: "true"
    
  frontend:
    image: priyanshugupta753/frontend:latest
    ports:
      - '3000:3000'
    environment:
      NEXTAUTH_SECRET: your_secret
      NEXTAUTH_URL: http://localhost:3000
      KEYCLOAK_ISSUER: http://192.168.200.226:8081/realms/LeaveApplication
      KEYCLOAK_CLIENT_ID: leave_application
      BACKEND_URL: http://192.168.200.226:8082
      NEXT_PUBLIC_BACKEND_URL: http://192.168.200.226:8082
      NEXT_PUBLIC_KEYCLOAK_ISSUER: http://192.168.200.226:8081/realms/LeaveApplication
      TEMPLATE_ID: 4
      NEXT_PUBLIC_TEMPLATE_ID: 4
    depends_on:
      - backend
